apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - prometheus-config.yaml
  - grafana-config.yaml
  - monitoring-services.yaml
  - monitoring-deployments.yaml
